### ISSUE TITLE
Schematron (XSLT)  ERROR on [BR-CO-17]-VAT category tax amount (BT-117) = VAT category taxable amount (BT-116) x (VAT category rate (BT-119) / 100), rounded to two decimals.

### ISSUE THREAD

**Issue by ReneVanOmmen** [phax/validation#303] opened 2021-11-30 18:36 UTC
Please help, 

We got schematron validation error on invoice which we believe is not correct.

![image](https://user-images.githubusercontent.com/17880207/144105628-a9c0679a-627f-48e0-abf3-35e0a528215a.png)

The BR-CO-17 rule compares (-325.00) with (-1710.50 * 0.19 = -324.995) but is rounded at 2 digits, which results in an error.

Is this a bug ? and how can it be solved?

            <ram:ApplicableTradeTax>
                <ram:CalculatedAmount>-325.00</ram:CalculatedAmount>
                <ram:TypeCode>VAT</ram:TypeCode>
                <ram:BasisAmount>-1710.50</ram:BasisAmount>
                <ram:CategoryCode>S</ram:CategoryCode>
                <ram:RateApplicablePercent>19.00</ram:RateApplicablePercent>
            </ram:ApplicableTradeTax>

[BR-CO-17]-VAT category tax amount (BT-117) = VAT category taxable amount (BT-116) x (VAT category rate (BT-119) / 100), rounded to two decimals.

Thanks

**Comment by phax** [comment] 2022-03-18 09:52
The same thing is also valid for UBL. Please see the attached example file:

[Test_BR_CO_17_UBL.xml.txt](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/8303439/Test_BR_CO_17_UBL.xml.txt)

**Comment by oriol** [comment] 2022-03-28 20:25
This example file does not raise BR-CO-17

**Comment by oriol** [comment] 2022-04-08 07:29
Closing the issue as we cannot reproduce the error

**Closed as completed by oriol** 2022-04-08 07:29 UTC
Labels: Format UBL, Format CII

**Comment by phax** [comment] 2022-04-08 08:06
The original error occurred with 1.3.3 of the validation artefacts and I confirm this.
I also checked with the 1.3.4 versions and could reproduce the error.
Since 1.3.5 the error is gone for the CII issue (fixed with #256 and 7337db6b37f72663d19bc2489bdd6776b69c2452 )

Errors in 1.3.4:
![grafik](https://user-images.githubusercontent.com/196219/162395486-9bbeaff7-bbe0-45df-aa93-1d3fe7b6efb5.png)

Error in 1.3.5:
![grafik](https://user-images.githubusercontent.com/196219/162395584-e897abdc-7bb5-4d54-8e38-7ac994f5a62d.png)

So this particular issue should have been solved with "XRechnung Schematron 1.6.0 compatible with XRechnung 2.1.1".
